# Generated by Django 4.2.1 on 2024-02-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('doctor_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('patient_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('patient_image', models.ImageField(blank=True, null=True, upload_to='patient_images/')),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consult_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('medicines', models.JSONField(default=list)),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.doctor')),
                ('patient_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.patient')),
            ],
            options={
                'db_table': 'consultation',
                'ordering': ['-date'],
            },
        ),
    ]
