# Generated by Django 4.2.1 on 2023-06-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDataTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restaurant', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('food', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('linkImg', models.URLField(max_length=500)),
                ('restaurantImg', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'FoodTest',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_id', models.IntegerField()),
                ('food', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('veg_non', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('price', models.IntegerField()),
                ('delivery_charge', models.IntegerField()),
                ('serving_distance', models.IntegerField()),
                ('prepration_time', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('rating', models.FloatField()),
                ('restaurant', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('indicator', models.IntegerField()),
            ],
            options={
                'db_table': 'RestDetails',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('restaurant_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('restaurant_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('restaurant_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user')),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('restaurant_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.restaurant')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
