# Generated by Django 4.2.1 on 2024-02-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medicines',
            field=models.TextField(default=list),
        ),
        migrations.CreateModel(
            name='PatientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.patient')),
            ],
            options={
                'db_table': 'patientLogin',
            },
        ),
        migrations.CreateModel(
            name='DoctorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FoodApp.doctor')),
            ],
            options={
                'db_table': 'doctorLogin',
            },
        ),
    ]
