# Generated by Django 4.2.1 on 2024-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_alter_consultation_medicines_patientlogin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.CharField(max_length=5)),
            ],
        ),
    ]
